### ISSUE TITLE
Deprecate global variables and functions (item(), exec(), _, items, current)

### ISSUE THREAD

**Issue by julienmoumne** [julienmoumne/hotshell#22]
The following variables and methods are globally available when defining menus :
 - item()
 - exec()
 - _
 - items
 - current

These references should be imported using regular "require" statements as in : 

```javascript
var item = require('hotshell').item
var exec = require('hotshell').exec
var _ = require('underscore')

item({desc: 'topten'}, function () {

    var topTen =
        'echo "history" | bash -i 2>/dev/null | sed "s/^ *[0-9]* *//" | ' +
        'sort | uniq -c | sort -nr | head | sed "s/^ *[0-9]* *//"'

    _(exec(topTen).split('\n')).each(function (el, ix) {
        item({key: ix, cmd: el})
    })
})
```

**Comment by Secathor** [comment]
Wow!
I'd not noticed this breaking change while upgrading HotShell to last version.
This add a lot of boilerplate code (like the Java's imports btw).
But I believe you made this change with good reason 😉

Maybe provide an "upgrade guide" when encountered these error messages:
```
ReferenceError: 'item' is not defined
motto: motto: ReferenceError: 'exec' is not defined
ReferenceError: '_' is not defined
```
Going to change all HotShell menus in several QS projects 🤘
