### ISSUE TITLE
Horizontal menu breadcrumb

### ISSUE THREAD

**Issue by hbeaufils** [julienmoumne/hotshell#9]
Following your recommandations after my pull request, I wanted to open a debate about display options.

It'd be nice to have a way to configure the display (per project like in my PR, or per user, or something else).

Maybe that a user configuration would be better, but what if a project owner wants to add some specific features to its hotshell menu ?

What do you think about it ?

**Comment by julienmoumne** [comment]
Hi Hadrien,

Thank you for your [pull request](https://github.com/julienmoumne/hotshell/pull/8)!

I really like the horizontal breadcrumb.

This is how it looked before: 

![before](https://cloud.githubusercontent.com/assets/723165/19089568/21d7e1d2-8a7b-11e6-92b3-eaea98c6661f.png)

This is how it looks after applying your pull request:

![after](https://cloud.githubusercontent.com/assets/723165/19089567/21d7a992-8a7b-11e6-8806-aef1dce95c2f.png)

This saves screen real estate and it's more intuitive.

I tried several variations but I think yours has the nicest look:

**Variation 1**

![variation-2](https://cloud.githubusercontent.com/assets/723165/19089569/21d7ed76-8a7b-11e6-8e76-d7a9da0e2c27.png)

**Variation 2**

![variation-1](https://cloud.githubusercontent.com/assets/723165/19089570/21d82aac-8a7b-11e6-9573-6950583248af.png)

I don't think we actually need a display option, it definitely works better with a horizontal alignment.

However, if we were to introduce display or hotkey configurations (see #10), I would definitely recommend storing them in `~\.hotshell` so it's specific to a user and not to a menu definition.
